# Generated by Django 4.2.6 on 2024-08-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers_alter_user_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authverification',
            name='code',
            field=models.IntegerField(),
        ),
    ]
