# Generated by Django 4.2.6 on 2024-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='authverification',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
