# Generated by Django 4.2.6 on 2024-08-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_authverification_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='authverification',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
